[package]
name = "RTWatch"
version = "0.1.0"
edition = "2021"

[dependencies]
scrap = "0.5"
ffmpeg-next = "7.0"

[target.x86_64-pc-windows-gnu]
linker = "gcc"

[target.x86_64-unknown-linux-gnu]
linker = "clang"